### ISSUE TITLE
Need wildcard in file pattern to facilitate handling  RINEX3 filename conventions

### ISSUE THREAD

**Issue by ccrook** [linz/liblinz-gnss-perl#5]
Quick questions about getdata.conf, does it accept wildcards in the filename?
3:19 PM
filename [SSSS]00*_R_[yyyy][ddd]0000_01D_30S_MO.crx.gz
3:19 PM
or
3:20 PM
filename [SSSS]00[A-Z][A-Z][A-Z]_R_[yyyy][ddd]0000_01D_30S_MO.crx.gz (edited) 
3:25 PM
Chris Crook No I am guessing not.  At the moment it is set up to build the required file name which it then uses explicitly the ftp or http(s) request.  Using wildcard would possibly require a new capability to get a directory listing - possibly messy, especially for https.
3:28 PM
Dionne Hansen That’s a bit tricky…. there is a 3 digit country code in the RINEX3 data - and CDDIS appears to only offer rinex 3 now.
3:30 PM
Scratch that. It looks like they are offering both still. :slightly_smiling_face:
3:43 PM
Dionne Hansen Some searching has turned up that this works: https://cddis.nasa.gov/archive/gps/data/daily/2021/080/21d/*?list
urs.earthdata.nasa.govurs.earthdata.nasa.gov
Earthdata Login
Earthdata Login

**Comment by ccrook** [comment]
Following further consideration (in [slack](https://linz.slack.com/archives/C01D9EDBY8M/p1627249003014600)) of the business requirement for handling RINEX3 filenames in getdata the following approach is suggested:

@Dionne I have had a play with wildcards and (bar testing) is implemented (though I also just notices the "scratch that" above.  However I am also wondering if we will need some capability around handling long filenames like this, and in particular in disambiguating (???) where the same code is used more than once.

I was thinking that it could be worth having an option to have a mapping code->id, and then use [id] rather than code in the remote data centres.   For codes not defined the default mapping would be id = code.

Probably I think the possible pattern would be something like:

<CodeList>
    Name: IGS
    <Mapping>
      ENAO   ENAO00PRT
       ...
    </Mapping>
</CodeList>

Each DataCenter could then have options using codes lists, eg:

<DataCenter>
     ....
    CodeLists IGS
    UseDefaultId True/False

</DataCenter>

The UseDefaultId would provide an option to disable the default id=code, so only listed codes would be used, which would allow renaming of files when they are retrieved..   Not sure how useful that would be if the mark name is unchanged in the file though - possibly only useful if the mark is renamed in the RINEX file itself.  I can't remember what handling of that is already embedded in our utilities :-(

**Comment by dnhansen50** [comment]
I see what you're saying re: more than one file option with the wildcard option. The code list sounds like a reasonable idea. 
For the time being, both RINEX2 and RINEX3 files are in the directory and to my knowledge there isn't a defined date where the RINEX2 files will cease, so if it isn't a convenient time to make the RINEX3 changes we can wait. Basically, it doesn't have to be part of our minimum viable product yet. :)

**Comment by ccrook** [comment]
Currently resolved by using approximate coordinate to identify when we have the correct station...
